### ISSUE TITLE
syntax error - both with VS and CLang

### ISSUE THREAD

**Issue by mediabuff** [PhillipVoyle/json_h#1]
1>C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(35,9): error : no type named 'shared_ptr' in namespace 'std'
1>     std::shared_ptr<TInterface>& m_t;
1>     ~~~~~^
1>C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(35,19): error : expected member name or ';' after declaration specifiers
1>     std::shared_ptr<TInterface>& m_t;
1>     ~~~~~~~~~~~~~~~^
1>C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(39,30): error : no type named 'shared_ptr' in namespace 'std'
1>     TryReadObjectFunctor(std::shared_ptr<TInterface>& t, TReader &reader, const std::string& type):m_t(t), m_reader(reader), m_type(type)
1>                          ~~~~~^
1>C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(39,40): error : expected ')'
1>     TryReadObjectFunctor(std::shared_ptr<TInterface>& t, TReader &reader, const std::string& type):m_t(t), m_reader(reader), m_type(type)
1>                                         ^
1>  C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(39,24) :  note: to match this '('
1>     TryReadObjectFunctor(std::shared_ptr<TInterface>& t, TReader &reader, const std::string& type):m_t(t), m_reader(reader), m_type(type)
1>                         ^
1>C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(70,6): error : no type named 'shared_ptr' in namespace 'std'
1>  std::shared_ptr<T> CreateAndRead(const InterfaceDescriptor<T> & descriptor, TReader &reader)
1>  ~~~~~^
1>C:\MyDevProjects\MyProjects\temp\json_h-master\/include\json/InterfaceDescriptor.h(70,16): error : expected unqualified-id
1>  std::shared_ptr<T> CreateAndRead(const InterfaceDescriptor<T> & descriptor, TReader &reader)
1>                 ^
1>  6 errors generated.

**Comment by PhillipVoyle** [comment]
It seems to be complaining about shared_ptr. Which flavour of the standard library are you using? I can maybe try to reproduce it. It's looking like you should just be able to #include the header with that class to work around it.  I think it's <memory> from recollection.  I'm away from my keyboard this week so feel free to raise a pull request if you have a fix. Otherwise I'll have a look when I get back.

**Comment by PhillipVoyle** [comment]
Added #include &lt;memory&gt; to InterfaceDescriptor.h

https://github.com/PhillipVoyle/json_h/commit/1f17d2df4a7e2c401ceec0692343d38f9c403fa2

also added build for VS2015
