### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by abdessattar** [PhillipVoyle/json_h#2]
Dear sir,

I am Abdessattar Bahri, engineering student, in proess of setting my graduation project which is related to your repository on github entitled "json_h".

I need to include this library to my project with visual studio 2015. To do this I must have the directories lib and include.
To obtain those , I have to compile this library.
So i need a help.
Hwo can I compile it?

Thank you in advance,

Best regards,

**Comment by PhillipVoyle** [comment]
Hi there,
you won't need a lib directory to use this in your project, and it doesn't compile on it's own. I'd start by making a c++ console project and having a look at the samples on the front page.

Happy hacking.

I'm happy to help if you have any specific problems related to the implementation.

**Comment by abdessattar** [comment]
Good morning,
I can use your library in project which is built by visual studio 2005 ? 
if no which version of visual studio I can work with.

**Comment by PhillipVoyle** [comment]
Hmm, 
I haven't tried that version of the toolset, but I know that the implementation of the templates has changed since back then. It's possible but I don't know for sure one way or the other.

Sorry
